# Generated by Django 5.2.4 on 2025-07-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact_always_notify_contact_important_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
