# Generated by Django 5.2.4 on 2025-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_first_name_contact_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'RQ Dashboard',
                'verbose_name_plural': 'RQ Dashboard',
            },
        ),
    ]
