# Generated by Django 5.2.4 on 2025-07-26 20:19

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('token_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_integrations', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImapIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', encrypted_model_fields.fields.EncryptedCharField()),
                ('port', models.PositiveIntegerField()),
                ('username', encrypted_model_fields.fields.EncryptedCharField()),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('use_ssl', models.BooleanField(default=True)),
                ('smtp_server', encrypted_model_fields.fields.EncryptedCharField()),
                ('smtp_port', models.PositiveIntegerField()),
                ('smtp_username', encrypted_model_fields.fields.EncryptedCharField()),
                ('smtp_password', encrypted_model_fields.fields.EncryptedCharField()),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imap_integrations', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutlookIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('tenant_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('token_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_integrations', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
