# Generated by Django 5.2.4 on 2025-07-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_integrations', '0001_initial'),
        ('users', '0005_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailintegration',
            name='watch_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gmailintegration',
            name='watch_expiration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailintegration',
            name='watch_resource_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gmailintegration',
            name='watch_topic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imapintegration',
            name='refresh_interval_seconds',
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AlterField(
            model_name='gmailintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='imapintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='outlookintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
