# Generated by Django 5.2.4 on 2025-07-28 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_integrations', '0002_gmailintegration_watch_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imapintegration',
            name='refresh_interval_seconds',
            field=models.PositiveIntegerField(default=900, validators=[django.core.validators.MinValueValidator(600, message='Minimum is 600 seconds (10 minutes)')]),
        ),
    ]
