# Generated by Django 5.2.4 on 2025-07-26 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_rename_first_name_contact_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='users.contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='users.userprofile')),
                ('to_contacts', models.ManyToManyField(blank=True, related_name='received_emails', to='users.contact')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('url', models.URLField(blank=True, help_text='Link to the attachment file', null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailthread'),
        ),
    ]
