# Generated by Django 5.2.4 on 2025-07-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(default='test', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='to_emails',
            field=models.TextField(blank=True, help_text='Raw string of recipient emails'),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailthread'),
        ),
    ]
