# Generated by Django 5.2.4 on 2025-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_from_email_email_to_emails_alter_email_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
