# Generated by Django 5.2.4 on 2025-07-26 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_from_email'),
        ('users', '0004_rename_first_name_contact_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='muted',
            field=models.BooleanField(default=False, help_text='Whether this whole thread was muted'),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, help_text='Plain text email body'),
        ),
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_contact',
            field=models.ForeignKey(blank=True, help_text='Sender contact linked to this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='users.contact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(help_text='Raw sender email address string', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='html_body',
            field=models.TextField(blank=True, help_text='HTML formatted email body'),
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this email', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='in_reply_to',
            field=models.CharField(blank=True, help_text='Message-ID of the email this one is replying to', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the email has been read'),
        ),
        migrations.AlterField(
            model_name='email',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Whether the email is marked as starred'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_id',
            field=models.CharField(help_text='Unique message ID from the email headers', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this email', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='email',
            name='received_at',
            field=models.DateTimeField(help_text='Date and time when the email was received'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(help_text='Email subject line', max_length=512),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='The thread this email belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailthread'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_contacts',
            field=models.ManyToManyField(blank=True, help_text='Linked recipient contacts', related_name='received_emails', to='users.contact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
    ]
