# Generated by Django 5.2.4 on 2025-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailthread_muted_alter_email_body_and_more'),
        ('users', '0005_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc_contacts',
            field=models.ManyToManyField(blank=True, help_text="Linked 'BCC' recipient contacts", related_name='bcced_emails', to='users.contact'),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_contacts',
            field=models.ManyToManyField(blank=True, help_text="Linked 'CC' recipient contacts", related_name='cced_emails', to='users.contact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_contacts',
            field=models.ManyToManyField(blank=True, help_text="Linked 'To' recipient contacts", related_name='received_emails', to='users.contact'),
        ),
    ]
