# Generated by Django 5.2.4 on 2025-07-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_email_bcc_contacts_email_cc_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='to_emails',
        ),
    ]
