# Generated by Django 5.2.4 on 2025-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_remove_email_to_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='direction',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], default='IN', help_text='Direction of the email relative to the user', max_length=3),
        ),
    ]
