# Generated by Django 5.2.4 on 2025-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_email_is_archived_email_is_draft_email_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received'), ('queued', 'Queued'), ('draft', 'Draft'), ('archived', 'Archived'), ('trashed', 'Trashed'), ('snoozed', 'Snoozed')], default='received', help_text='Status of the email', max_length=10),
        ),
    ]
