# Generated by Django 5.0.4 on 2025-07-31 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
