# Generated by Django 5.0.4 on 2025-07-31 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_emailattachment_created_at_emailattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public token for accessing this attachment', unique=True),
        ),
    ]
