# Generated by Django 5.0.4 on 2025-07-31 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_emailattachment_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='public_token_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
