# Generated by Django 5.0.4 on 2025-07-31 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_emailattachment_download_count_and_more'),
        ('users', '0005_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='owner',
            field=models.ForeignKey(default='46e8e5af-5819-49d1-a341-5b19cd5e22dc', on_delete=django.db.models.deletion.CASCADE, related_name='email_attachments', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
